import type { Metadata } from 'next'
import { AuthProvider } from '@/context/AuthContext'
import './styles/globals.css'
import './styles/theme.css'
import '@fortawesome/fontawesome-free/css/all.min.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 antialiased">
        <AuthProvider>
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
