import type { Metadata } from 'next'
import '../styles/globals.css'
import '../styles/theme.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function DashboardLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return <section>{children}</section>
}
